BlogWebsite/BlogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


# handler404 = 'main.views.view_404'

BlogWebsite/main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('new/post/', views.add_post, name="add_post"),
    path("post/detail/<post_id>/", views.post_detail, name="post_detail"),
    path("post/update/<post_id>/", views.update_post, name="update_post"),
    path("post/delete/<post_id>/", views.delete_post, name="delete_post"),
    path("post/all/", views.all_posts, name="all_posts"),
    path('search/', views.search, name='search')
]

BlogWebsite/main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    is_published = models.BooleanField()
    published_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', default='images/default_img.jpg')
    
    # class Category(models.TextChoices):
    #     GENERAL = 'General'
    #     SCIENCE = 'Science'
    #     CULTURE = 'Culture'
    #     FOOD = 'Food'
    #     TECH = 'Tech'
    #     FASHION = 'Fashion'

    Categories = models.TextChoices('Category', ["General","Science", "Culture", "Food","Tech","Fashion"]) 
    category = models.CharField(max_length = 64, choices = Categories.choices)

BlogWebsite/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from .models import Post

from datetime import date, timedelta
# from django.db.models import Q
# Create your views here.

def home(request:HttpRequest):
    if "pub" in request.GET:
        posts = Post.objects.filter(is_published = request.GET.get("pub", default=True))[0:3]
    else:
        posts = Post.objects.all().filter(is_published = request.GET.get("pub", True))[0:3]

    return render(request, "main/home.html", {"posts" : posts})

def add_post(request:HttpRequest):

    if request.method == 'POST':
        try:
            new_post = Post(
                title = request.POST["title"], 
                content = request.POST["content"], 
                is_published = request.POST.get("is_published", False), 
                image = request.FILES.get("image", Post.image.field.default),
                category = request.POST['category']
            )
            new_post.save()
            
        except Exception as e:
            print(e)
        return redirect("main:home")
    
    
    return render(request, "main/add_post.html", {'category' : Post.Categories.choices})

def post_detail(request:HttpRequest, post_id):

    try:
        #getting a  post detail
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        return render(request, "404.html")
    except Exception as e:
        print(e)

    return render(request, "main/post_detail.html", {"post" : post})


def update_post(request:HttpRequest, post_id):
        try:
            post = Post.objects.get(pk=post_id)
        except Post.DoesNotExist:
            return render(request, "404.html")

        if request.method == "POST":
            try:
                post.title = request.POST["title"]
                post.content = request.POST["content"]
                post.is_published = request.POST.get("is_published", False)
                post.image = request.FILES.get('image', post.image)
                post.category = request.POST['category']
                post.save()
            except Post.DoesNotExist:
                return render(request, "404.html")
            except Exception as e:
                print(e)
            return redirect("main:post_detail", post_id= post.id)

        return render(request, 'main/update_post.html', {"post" : post, 'category' : Post.Categories.choices})


def delete_post(request:HttpRequest, post_id):

    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        return render(request, "404.html")
    
    try:
        post.delete()
    except Exception as e:
        print(e)
    
    return redirect("main:home")

def all_posts(request: HttpRequest):

    
    if "cat" in request.GET:
        posts = Post.objects.filter(category = request.GET["cat"])
    else:
        posts = Post.objects.all().order_by("-published_at") 
    
        #calculate the page content
    limit = 3
    pages_count = [str(n) for n in range(1, round(posts.count()/limit)+1)] #use list comprehension to convert number to string number
    start = (int(request.GET.get("page", 1))-1)*limit
    end = (start)+limit

    print(list(pages_count))


    #apply the limit/slicing
    posts = posts[start:end]

    # print(start, end)

    return render(request, "main/all_post.html", {"posts" : posts, "category" : Post.Categories.choices, "pages_count":pages_count})

def search(request: HttpRequest):
    posts = []
    try: 
        if "search" in request.GET:
            posts = Post.objects.filter(title__contains=request.GET["search"])

        if "date" in request.GET and len(request.GET["date"]) > 4:
            first_date = date.fromisoformat(request.GET["date"])
            end_date = first_date + timedelta(days=1)
            posts = posts.filter(published_at__gte=first_date, published_at__lt=end_date)
    except Exception as e:
        print(e)
    
    context = {"posts" : posts}
    return render(request,"main/search_result.html", context)

# def view_404(request, exception):
#     return render(request, '404.html')

BlogWebsite/main/templates/main/add_post.html
{% extends 'main/base.html' %}

{% block title %} Add New Post {% endblock %}

{% block content %}
<div class="row">
    <h1>Add new post</h1>
    <div class="col">

        <form action="{% url 'main:add_post' %}" method="post" enctype="multipart/form-data" class="d-flex flex-column gap-2">
            {% csrf_token %}

            <input name="title" type="text" placeholder="Title" class="form-control" required minlength="5" />
            <textarea name="content" class="form-control" required ></textarea>

            <div class="form-check form-switch">
                <input name="is_published" value="True" class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                <label class="form-check-label" for="flexSwitchCheckDefault">is publihed</label>
            </div>

                <h5>Category:</h5>
                <select name="category" class="form-select" aria-label="Default select example">
                    {% for val, cat in category %}
                        <option value={{val}}>{{cat}}</option>
                    {% endfor %}
                </select>

            <h5>Choose Image:</h5>
            <input name="image"  type="file"  accept="image/*" class="form-control"/>

            <input type="submit" class="btn btn-dark" value="Add Post" style="background: linear-gradient(#191970, #171765, #14145a, #12124e, #0f0f43, #0d0d38, #0a0a2d, #080822, #050516, #02020b);"/>
        </form>
    </div>

</div>
{% endblock %}

BlogWebsite/main/templates/main/all_post.html
{% extends 'main/base.html' %}

{% block title %} BLOG | ALL POST {% endblock %}


{% block content %}

<div class="row g-4">

    <div class="d-flex justify-content-between align-items-center">
        <h2>{% if 'cat' in request.GET %} {{request.GET.cat}} {% else %} All {% endif %}Posts ({{ posts.count }}) </h2>
    </div>

</div>

<div class="row">
    <div class="col">
        <div class="d-flex gap-2 justify-content-center">
            <a href="{% url 'main:all_posts' %}" class="p-2 ps-3 pe-3 rounded-pill cat  text-decoration-none  {% if 'cat' not in request.GET %} All  {% endif %}">All</a>
            {% for val, key in category %}
                <a href="?cat={{val}}" class="p-2 ps-3 pe-3 rounded-pill cat {% if request.GET.cat == val %} {{ val }}{% endif %} text-decoration-none">{{val}}</a>
            {% endfor %}
        </div>
    </div>
</div>

    <div class="row mt-2 g-5">

        {% for post in posts %}
            <div class="col-4">
                <div class="HS d-flex flex-column gap-2 border border-1 shadow p-3 rounded-4 h-100">
                    <img src="{{ post.image.url }}"  class="w-100 rounded-4"/>
                    <h6 class="cat pt-1 pb-1 ps-3 pe-3 rounded-pill {{post.category}} ">{{ post.category }}</h6>
                    <h3><a href="{% url 'main:post_detail' post.id  %}" style="color: rgba(0, 0, 0, 0.582); text-decoration:none;">{{post.title}}</a></h3>
                    <h6 class="text-muted">{{ post.published_at }}</h6>
                    <small>{{ post.is_published }}</small>
                    
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row mt-5">
        <div class="col d-flex gap-2 justify-content-center">
            {% for page in pages_count %}
                <a href="?page={{page}}{% if 'cat' in request.GET %}&cat={{request.GET.cat}}{% endif %}" class="btn border {% if request.GET.page == page %} btn-primary {% elif page == '1' and 'page' not in request.GET %} btn-primary {% endif %}">{{page}}</a>
            {% endfor %}
        </div>

    </div>
{% endblock %}

BlogWebsite/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <!-- FavIcon -->
        <link rel="icon" href="images/cat.jpeg" type="img/icon">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <style>
            .HS {
                animation: fade-out 0.6s ease-in;
            }
            @keyframes fade-out {

                from {
                    opacity: 0;
                    transform: translate(0, 100px);
                }

                to {
                    opacity: 1;
                    transform: translate(0, 0px);
                }
            }
        </style>

        <!-- Google Icon -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        
        <!-- CSS Library -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body style="background: linear-gradient(#ffffff, #5e65b6); background-attachment:  fixed;">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-md fixed-top" data-bs-theme="dark" 
    style="background: linear-gradient(#191970, #171765, #14145a, #12124e, #0f0f43, #0d0d38, #0a0a2d, #080822, #050516, #02020b);">

        <!-- Container wrapper -->
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
            <span class="material-symbols-rounded">box</span> BLOG</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main:all_posts' %}">POST</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main:search' %}">SEARCH</a>
                    </li> -->
                </ul>
            </div> <!-- Collapsible wrapper -->
            <form action="{% url 'main:search' %}" class="d-flex" role="search" method="get">
                <input class="form-control me-2 bg-light text-dark" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
        </div> <!-- Container wrapper -->
    </nav> <!-- Navbar -->

        <div class="container mt-5 pt-5">
        {% block content %}

        {% endblock %}
        </div>

            <!-- Footer -->
    <div class="container">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
          </ul>
          <p class="text-center text-body-secondary">© 2024 Blogger, Inc</p>
        </footer>
      </div>
  
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

BlogWebsite/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %} Blog Website {% endblock %}

{% block content %}
<div class="row">

    <div class="col"><h1>Latest Posts</h1>
        <div class="d-flex gap-2 justify-content-end align-items-center">
            
            <a class="btn btn-dark" href="{% url 'main:add_post' %}" style="background: linear-gradient(#191970, #171765, #14145a, #12124e, #0f0f43);">Add Post</a>
            <a class="btn btn-dark" href="{% url 'main:all_posts' %}" style="background: linear-gradient( #0d0d38, #0a0a2d, #080822, #050516, #02020b);">View All</a>

        </div>

        <!-- <div class="d-flex justify-content-end align-items-center">
            <a class="btn btn-dark" href="{% url 'main:all_posts' %}" style="background: linear-gradient( #0d0d38, #0a0a2d, #080822, #050516, #02020b);">View All</a>
        </div> -->
        <div class="row mt-4">
            
            {% for post in posts %}
            <div class="col-4">
                <div class="HS d-flex flex-column gap-1 border border-1 shadow p-3 rounded-4 h-100">
                    <img src="{{ post.image.url }}"  class="w-100 rounded-4"/>
                    <h6 class="cat pt-1 pb-1 ps-3 pe-3 rounded-pill {{post.category}} ">{{ post.category }}</h6>
                    <h3><a href="{% url 'main:post_detail' post.id  %}" class="text-decoration-none" style="color: rgba(0, 0, 0, 0.582);">{{post.title}}</a></h3>
                    <h6 class="text-muted">{{ post.published_at }}</h6>
                    <a href="?pub={{post.is_published}}" style="color: black; text-decoration: none;"><small>{{ post.is_published }}</small></a>

                </div>
            </div>
            {% endfor %}
        
        </div>
        
    </div>
</div>
{% endblock %}

BlogWebsite/main/templates/main/post_detail.html
{% extends 'main/base.html' %}

{% block title %} BLOG | {{post.title}} {% endblock %}


{% block content %}
    <div class="row">
        
        <div class="col">
            <div class="d-flex flex-column gap-2">
                <h1>{{ post.title }}</h1>
                <img src="{{ post.image.url }}"  class="rounded-4" style="background-size: cover; width: 100%; height: 300px;"/>
                
                <h6 class="cat pt-1 pb-1 ps-3 pe-3 rounded-pill {{ post.category }}">{{ post.category }}</h6>
                
                <div class="d-flex justify-content-between">
                    <h6>{{post.published_at}}</h6>
                    <div class="d-flex gap-2">
                        <a href="{% url 'main:update_post' post.id %}" class="btn btn-primary"><span class="material-symbols-rounded">
                            edit
                            </span></a>
                        <a href="{% url 'main:delete_post' post.id %}" class="btn btn-danger"><span class="material-symbols-rounded">
                            delete
                            </span></a>
                    </div>
                    
                </div>
                
                <p>{{ post.content }}</p>
            </div>

        </div>


    </div>
{% endblock %}

BlogWebsite/main/templates/main/search_result.html
{% extends 'main/base.html' %}

{% block title %} BLOG | SEARCH RESULT {% endblock %}

{% block content %}
<div class="row">
    <div class="d-flex flex-column gap-2">
            
        <h1>Search</h1>
        <form action="{% url 'main:search' %}"  method="get" class="d-flex gap-2">
            <input type="search" class="form-control" name="search" value="{{request.GET.search}}" placeholder="Search..."/>
            <input type="date" class="form-control" style="width: 200px;" name="date" value="{{request.GET.date}}"/>
            <input type="submit" value="Search" class="btn btn-outline-dark" />
        </form> 

        <h2>Search results for {{ request.GET.search }} ({{ posts.count }}) </h2>
    </div>
</div>

<div class="row">
    {% for post in posts %}
    <div class="col-4">
        <div class="d-flex flex-column gap-1 border border-1 shadow p-3 rounded-4 h-100">
            <img src="{{ post.image.url }}"  class="w-100 rounded-4"/>
            <h6 class="cat pt-1 pb-1 ps-3 pe-3 rounded-pill {{post.category}} ">{{ post.category }}</h6>
            <h3><a href="{% url 'main:post_detail' post.id  %}" class="text-decoration-none">{{post.title}}</a></h3>
            <h6 class="text-muted">{{ post.published_at }}</h6>
            <a href="?pub={{post.is_published}}" style="color: black; text-decoration: none;"><small>{{ post.is_published }}</small></a>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

BlogWebsite/main/templates/main/update_post.html
{% extends 'main/base.html' %}

{% block title %} BLOG | Update Post {% endblock %}


{% block content %}
    <div class="row">
        <h1>Update post</h1>
        <div class="col">

            <form action="{% url 'main:update_post' post.id %}" enctype="multipart/form-data" method="post" class="d-flex flex-column gap-2">
                {% csrf_token %}

                <input name="title" type="text" placeholder="Title" class="form-control" required minlength="5" value="{{ post.title }}" />
                <textarea name="content" class="form-control" >{{post.content}}</textarea>

                <div class="form-check form-switch">
                    <input name="is_published" value="True" class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" {% if post.is_published %} checked {% endif %}>
                    <label class="form-check-label" for="flexSwitchCheckDefault">is publihed</label>
                </div>

                <h5>Category:</h5>
                <select name="category" class="form-select" aria-label="Default select example">
                    {% for val, cat in category %}
                        <option value={{val}} {% if post.category == val %} selected {% endif %}>{{cat}}</option>
                    {% endfor %}
                </select>


                <h5>Choose Image:</h5>
                <img src="{{ post.image.url }}" class="thumb" />
                <input name="image"  type="file" accept="image/*" class="form-control"/>

                <input type="submit" class="btn btn-dark" value="Update" style="background: linear-gradient(#191970, #171765, #14145a, #12124e, #0f0f43, #0d0d38, #0a0a2d, #080822, #050516, #02020b);"/>
            </form>

        </div>

    </div>
{% endblock %}